volumes:
  rteknoloji_static_volume: { }
  rteknoloji_media_volume: { }

services:
  django:
    container_name: rteknoloji
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - ./logs:/app/logs   # LOG PATH FIX
      - rteknoloji_static_volume:/app/staticfiles
      - rteknoloji_media_volume:/app/mediafiles
    environment:
      DB_MAIN_NAME: rteknoloji_main_db
      DB_MAIN_USER: rteknoloji_dbusr
      DB_MAIN_PASSWORD: pass123456*
      DB_MAIN_HOST: db_rteknoloji
      DB_MAIN_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      db_rteknoloji:
        condition: service_healthy

  db_rteknoloji:
    image: postgres:17
    restart: always
    volumes:
      - ./db/db_main_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: rteknoloji_main_db
      POSTGRES_USER: rteknoloji_dbusr
      POSTGRES_PASSWORD: pass123456*
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rteknoloji_dbusr -d rteknoloji_main_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
