"""
Django settings for rteknoloji project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from pathlib import Path
import environ

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent.parent  # settings > rteknoloji > BASE_DIR
PROJECT_DIR = BASE_DIR / "rteknoloji"
LOCALE_PATHS = [
    os.path.join(BASE_DIR, 'locale'),
]

# Env
env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / ".env")

# Settings
DEBUG = env("DEBUG")
SECRET_KEY = env("SECRET_KEY")
# Application definition

INSTALLED_APPS = [
    "home",
    "search",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.settings",
    "wagtail.contrib.simple_translation",
    "wagtail.locales",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'django.contrib.sitemaps',
    "pofo.apps.PofoConfig",
]

MIDDLEWARE = [
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

ROOT_URLCONF = "rteknoloji.urls"

TEMPLATES = [
    {
        "BACKEND" : "django.template.backends.django.DjangoTemplates",
        "DIRS"    : [
            os.path.join(PROJECT_DIR, "templates"),
        ],
        "APP_DIRS": True,
        "OPTIONS" : {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.i18n",
            ],
        },
    },
]

WSGI_APPLICATION = "rteknoloji.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
def get_secret(secret_name):
    try:
        with open(secret_name) as f:
            return f.read().strip()
    except IOError:
        return None


DATABASES = {
    'default': {
        'ENGINE'  : 'django.db.backends.postgresql_psycopg2',
        'NAME'    : os.getenv('DB_MAIN_NAME'),
        'USER'    : os.getenv('DB_MAIN_USER'),
        'PASSWORD': os.getenv('DB_MAIN_PASSWORD'),
        'HOST'    : os.getenv('DB_MAIN_HOST', 'db_rteknoloji'),
        'PORT'    : '5432',
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "tr"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    os.path.join(PROJECT_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "/static/"

MEDIA_ROOT = os.path.join(BASE_DIR, "mediafiles")
MEDIA_URL = "/media/"

# Default storage settings, with the staticfiles storage updated.
# See https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-STORAGES
STORAGES = {
    "default"    : {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    # ManifestStaticFilesStorage is recommended in production, to prevent
    # outdated JavaScript / CSS assets being served from cache
    # (e.g. after a Wagtail upgrade).
    # See https://docs.djangoproject.com/en/5.2/ref/contrib/staticfiles/#manifeststaticfilesstorage
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000

# Wagtail settings

WAGTAIL_I18N_ENABLED = True

WAGTAIL_CONTENT_LANGUAGES = LANGUAGES = [
    ('tr', "Turkish"),
    ('en', "English"),
]
WAGTAILSIMPLETRANSLATION_SYNC_PAGE_TREE = True

WAGTAIL_SITE_NAME = "rteknoloji"
# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://example.com"

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip', "mp4"]

SMTP_SERVER = env("SMTP_SERVER")
SMTP_PORT = env("SMTP_PORT")
SMTP_INFO_MAIL = env("SMTP_INFO_USERNAME")
SMTP_MANAGER_MAIL = env("SMTP_MANAGER_MAIL")
SMTP_PASSWORD = env("SMTP_PASSWORD")

# =========================
# Error reporting & logging
# =========================
# Where to write log files (make sure this directory exists and is writable)
# Prefer an external mount at /app/logs if present (compose.prod.yaml binds ./logs -> /app/logs)
_env_log_dir = env("LOG_DIR", default=None)
if _env_log_dir:
    LOG_DIR = Path(_env_log_dir)
elif Path("/app/logs").exists():
    LOG_DIR = Path("/app/logs")
else:
    LOG_DIR = BASE_DIR / "logs"
# Ensure the log directory exists to prevent handler configuration failures
try:
    LOG_DIR.mkdir(parents=True, exist_ok=True)
except Exception:
    # If we can't create it (permissions, etc.), file handlers will be delayed and
    # Django will still start; logs will go to console until directory becomes writable.
    pass

# Determine whether we can write into the log directory; if not, avoid file handlers
try:
    CAN_WRITE_LOGS = os.access(LOG_DIR, os.W_OK)
except Exception:
    CAN_WRITE_LOGS = False

FILE_HANDLERS = ["file_info", "file_error"] if CAN_WRITE_LOGS else []
X_FRAME_OPTIONS = "SAMEORIGIN"
# Admins who will receive error emails when DEBUG=False
# Provide a comma-separated list of emails via ADMIN_EMAILS env, e.g. "ops@example.com,dev@example.com"
# _admin_emails = env("ADMIN_EMAILS", default="")
# if _admin_emails:
#     ADMINS = [("Site Admin", email.strip()) for email in _admin_emails.split(",") if email.strip()]
# else:
#     ADMINS = []
#
# # Configure Django email backend for error emails (mail_admins)
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = SMTP_SERVER
# EMAIL_PORT = int(SMTP_PORT) if SMTP_PORT else 465
# EMAIL_HOST_USER = SMTP_INFO_MAIL
# EMAIL_HOST_PASSWORD = SMTP_PASSWORD
# EMAIL_USE_SSL = True  # matches SMTP_SSL used in mail service
# DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default=SMTP_INFO_MAIL or "webmaster@localhost")
# SERVER_EMAIL = env("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "formatters": {
        "verbose": {
            "format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s",
        },
        "simple": {
            "format": "[%(levelname)s] %(name)s: %(message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG" if DEBUG else "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": ["require_debug_true"],
        },
        "file_info": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "app.info.log"),
            "maxBytes": 5 * 1024 * 1024,  # 5MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "file_error": {
            "level": "ERROR",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(LOG_DIR, "app.error.log"),
            "maxBytes": 5 * 1024 * 1024,
            "backupCount": 10,
            "formatter": "verbose",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "filters": ["require_debug_false"],
            "include_html": True,
        },
    },
    "loggers": {
        "": {  # root logger for our project apps
            "handlers": ["console", "file_info", "file_error"],
            "level": "INFO",
        },
        "django": {
            "handlers": ["console", "file_info"],
            "level": "INFO",
            "propagate": False,
        },
        # 500 errors triggered by Django request handling
        "django.request": {
            "handlers": ["mail_admins", "file_error"],
            "level": "ERROR",
            "propagate": False,
        },
        "django.server": {
            "handlers": ["file_error"],
            "level": "ERROR",
            "propagate": False,
        },
    },
}

# Optional: Sentry integration if DSN provided (imported dynamically to avoid hard dependency)
SENTRY_DSN = env("SENTRY_DSN", default=None)
if SENTRY_DSN:
    try:
        import importlib

        sentry_sdk = importlib.import_module("sentry_sdk")
        DjangoIntegration = importlib.import_module("sentry_sdk.integrations.django").DjangoIntegration

        sentry_sdk.init(
            dsn=SENTRY_DSN,
            integrations=[DjangoIntegration()],
            traces_sample_rate=float(env("SENTRY_TRACES_SAMPLE_RATE", default=0.0)),
            send_default_pii=True,
            environment=env("SENTRY_ENV", default=("production" if not DEBUG else "development")),
        )
    except Exception:
        # Sentry is optional; ignore if not installed or fails to init
        pass
