# Generated by Django 5.2.7 on 2025-10-30 18:46

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Proje Açıklaması')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Proje İletişim',
                'verbose_name_plural': 'Proje İletişim Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Platform name')),
                ('icon', models.CharField(blank=True, choices=[('fa-brands fa-instagram', 'instagram'), ('fa-brands fa-facebook-f', 'facebook'), ('fa-brands fa-x-twitter', 'x'), ('fa-brands fa-youtube', 'youtube'), ('fa-brands fa-whatsapp', 'whatsapp')], null=True, verbose_name='Icon')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Social Media Platform',
                'verbose_name_plural': 'Social Media Platforms',
            },
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('slider_section', 11), ('about_section', 16), ('masonry_portfolio_section', 23), ('counter_section', 29), ('parallax_info_section', 40), ('clients_slider_section', 47), ('latest_blog_section', 57)], block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Banner Image can be 1950x750 px', 'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'help_text': 'Enter the main title of the banner', 'required': False}), 2: ('wagtail.blocks.TextBlock', (), {'help_text': 'Enter the subtitle of the banner', 'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter the external link', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the link text', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('external_link', 3), ('link_text', 4)]], {}), 6: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Enter the internal link', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('internal_link', 6), ('link_text', 4)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('external_link', 5), ('internal_link', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('image', 0), ('main_title', 1), ('sub_title', 2), ('link', 9)]], {}), 11: ('wagtail.blocks.ListBlock', (10,), {}), 12: ('wagtail.blocks.CharBlock', (), {'max_length': 255}), 13: ('wagtail.blocks.RichTextBlock', (), {}), 14: ('wagtail.blocks.StructBlock', [[('icon', 12), ('title', 12), ('description', 13)]], {}), 15: ('wagtail.blocks.ListBlock', (14,), {'icon': 'list-ul', 'label': 'Feature items', 'required': False}), 16: ('wagtail.blocks.StructBlock', [[('features_items', 15)]], {}), 17: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Left column image (900×650 px önerilir)'}), 18: ('wagtail.blocks.CharBlock', (), {'default': 'Responsive, convenient and multipurpose theme', 'max_length': 255}), 19: ('wagtail.blocks.RichTextBlock', (), {'default': 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.'}), 20: ('wagtail.blocks.CharBlock', (), {'default': 'About Company', 'max_length': 40}), 21: ('wagtail.blocks.URLBlock', (), {'required': False}), 22: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Right column image (900×650 px önerilir)'}), 23: ('wagtail.blocks.StructBlock', [[('left_image', 17), ('heading', 18), ('paragraph', 19), ('button_text', 20), ('button_link', 21), ('right_image', 22)]], {}), 24: ('wagtail.blocks.CharBlock', (), {'help_text': 'İkon CSS sınıfı, ör. "icon-desktop"', 'max_length': 120}), 25: ('wagtail.blocks.IntegerBlock', (), {'default': 350, 'help_text': 'Sayaçta gösterilecek sayı', 'min_value': 0}), 26: ('wagtail.blocks.CharBlock', (), {'default': 'Happy Clients', 'max_length': 80}), 27: ('wagtail.blocks.StructBlock', [[('icon_class', 24), ('number', 25), ('label', 26)]], {}), 28: ('wagtail.blocks.ListBlock', (27,), {'help_text': 'Sayaç öğeleri ekleyin', 'min_num': 1}), 29: ('wagtail.blocks.StructBlock', [[('items', 28)]], {}), 30: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Full-width parallax background (1920×1200 önerilir)'}), 31: ('wagtail.blocks.CharBlock', (), {'default': '0.6', 'help_text': 'data-parallax-background-ratio değeri (örn. "0.6")', 'max_length': 4, 'required': False}), 32: ('wagtail.blocks.CharBlock', (), {'default': 'bg-extra-dark-gray', 'help_text': 'Opacity div’ine verilecek sınıf (örn. "bg-extra-dark-gray")', 'max_length': 30, 'required': False}), 33: ('wagtail.blocks.CharBlock', (), {'default': 'opacity-medium', 'help_text': 'Opacity yoğunluğu sınıfı (örn. "opacity-medium")', 'max_length': 30, 'required': False}), 34: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Sol taraftaki illüstrasyon (ör. PNG, genişlik ~900px)'}), 35: ('wagtail.blocks.CharBlock', (), {'default': 'Unique, truly responsive and functional websites', 'max_length': 255}), 36: ('home.models.BulletLineBlock', (), {}), 37: ('wagtail.blocks.ListBlock', (36,), {'help_text': 'Madde satırları'}), 38: ('wagtail.blocks.CharBlock', (), {'default': 'GET TO KNOW US', 'max_length': 40}), 39: ('wagtail.blocks.URLBlock', (), {'help_text': 'Buton URL', 'required': False}), 40: ('wagtail.blocks.StructBlock', [[('background_image', 30), ('parallax_ratio', 31), ('overlay_color', 32), ('overlay_opacity_class', 33), ('left_image', 34), ('heading', 35), ('paragraph', 19), ('bullet_list', 37), ('button_text', 38), ('button_link', 39)]], {}), 41: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 42: ('wagtail.blocks.CharBlock', (), {'default': 'Company Name', 'max_length': 120}), 43: ('wagtail.blocks.CharBlock', (), {'default': 'Work Description', 'max_length': 220}), 44: ('wagtail.blocks.URLBlock', (), {'help_text': 'Logo tıklandığında gidilecek URL', 'required': False}), 45: ('wagtail.blocks.StructBlock', [[('logo', 41), ('company_name', 42), ('work_description', 43), ('link', 44)]], {}), 46: ('wagtail.blocks.ListBlock', (45,), {'help_text': 'Slider’a eklenecek logolar', 'min_num': 1}), 47: ('wagtail.blocks.StructBlock', [[('logos', 46)]], {}), 48: ('wagtail.blocks.CharBlock', (), {'default': 'Publish what you think', 'max_length': 120}), 49: ('wagtail.blocks.CharBlock', (), {'default': 'Latest Blogs', 'max_length': 120}), 50: ('wagtail.blocks.DateBlock', (), {'help_text': 'Yayın tarihi'}), 51: ('wagtail.blocks.CharBlock', (), {'default': 'John Doe', 'max_length': 60}), 52: ('wagtail.blocks.CharBlock', (), {'default': 'Post title', 'max_length': 120}), 53: ('wagtail.blocks.URLBlock', (), {'required': True}), 54: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Kısa özet (en fazla 220 karakter)', 'max_length': 220, 'required': False}), 55: ('wagtail.blocks.StructBlock', [[('image', 41), ('published_date', 50), ('author_name', 51), ('author_url', 21), ('title', 52), ('post_link', 53), ('excerpt', 54)]], {}), 56: ('wagtail.blocks.ListBlock', (55,), {'help_text': 'Gösterilecek blog yazıları', 'min_num': 1}), 57: ('wagtail.blocks.StructBlock', [[('small_label', 48), ('heading', 49), ('posts', 56)]], {})}, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.CreateModel(
            name='EmptyPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Enter the description of the Page', null=True)),
                ('in_sitemap', models.BooleanField(default=True)),
                ('in_sidebar', models.BooleanField(default=False)),
                ('body', wagtail.fields.StreamField([('blog_section', 8), ('contact_section', 32), ('about_us_section', 51), ('clients_slider_section', 58)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Tekil bir görsel ekleyin.', 'required': False}), 1: ('wagtail.blocks.URLBlock', (), {'help_text': "Video URL'si (YouTube, Vimeo vb.)", 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Slider için birden fazla görsel ekleyin.', 'required': False}), 4: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Galeri için birden fazla görsel ekleyin.', 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('video', 1), ('slider', 3), ('gallery', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {'help_text': 'Bir veya birden fazla medya bloğu ekleyin.', 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Blog içeriğini buraya girin.', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('blog_media', 6), ('description', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'default': 'Help us', 'max_length': 120}), 10: ('wagtail.blocks.CharBlock', (), {'default': 'We are here to help', 'max_length': 120}), 11: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'features': ['bold', 'italic', 'link'], 'help_text': 'Enter the description of the Page', 'null': True}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('subtitle', 10), ('paragraph', 11)]], {'rquired': False}), 13: ('wagtail.blocks.URLBlock', (), {'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'default': 'icon-map text-deep-pink icon-medium margin-25px-bottom', 'max_length': 120}), 15: ('wagtail.blocks.RichTextBlock', (), {'blank': True, 'null': True}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('icon', 14), ('address', 16)]], {}), 18: ('wagtail.blocks.ListBlock', (17,), {'required': False}), 19: ('wagtail.blocks.CharBlock', (), {'default': 'icon-phone text-deep-pink icon-medium margin-25px-bottom', 'max_length': 120}), 20: ('wagtail.blocks.RichTextBlock', (), {'null': True}), 21: ('wagtail.blocks.ListBlock', (20,), {}), 22: ('wagtail.blocks.StructBlock', [[('icon', 19), ('phone', 21)]], {}), 23: ('wagtail.blocks.ListBlock', (22,), {'required': False}), 24: ('wagtail.blocks.CharBlock', (), {'default': 'icon-mail text-deep-pink icon-medium margin-25px-bottom', 'max_length': 120}), 25: ('wagtail.blocks.StructBlock', [[('icon', 24), ('email', 21)]], {}), 26: ('wagtail.blocks.ListBlock', (25,), {'required': False}), 27: ('wagtail.blocks.CharBlock', (), {'default': 'icon-clock text-deep-pink icon-medium margin-25px-bottom', 'max_length': 120}), 28: ('wagtail.blocks.RichTextBlock', (), {}), 29: ('wagtail.blocks.ListBlock', (28,), {}), 30: ('wagtail.blocks.StructBlock', [[('icon', 27), ('working_hours', 29)]], {}), 31: ('wagtail.blocks.ListBlock', (30,), {'required': False}), 32: ('wagtail.blocks.StructBlock', [[('contact_help_section', 12), ('contact_image', 2), ('contact_video', 13), ('contact_address', 18), ('contact_phone', 23), ('contact_email', 26), ('contact_working_hours', 31)]], {}), 33: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ana başlık (örn: Gücünü Deneyimden Alan Çözümler)', 'required': True}), 34: ('wagtail.blocks.TextBlock', (), {'help_text': 'Alt açıklama / slogan (örn: Yılların tecrübesini, yenilikçi bakış açısıyla birleştiriyoruz.)', 'required': False}), 35: ('wagtail.blocks.StructBlock', [[('title', 33), ('subtitle', 34)]], {}), 36: ('wagtail.blocks.CharBlock', (), {'help_text': 'Firma Yöneticisi  Ad Soyad', 'required': False}), 37: ('wagtail.blocks.CharBlock', (), {'help_text': 'Ünvan', 'required': False}), 38: ('wagtail.blocks.CharBlock', (), {'help_text': 'Meslek', 'required': False}), 39: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Firma görseli', 'required': False}), 40: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Firma profili açıklaması', 'required': True}), 41: ('wagtail.blocks.StructBlock', [[('company_manager', 36), ('manager_title', 37), ('manager_jobs', 38), ('image', 39), ('description', 40)]], {}), 42: ('wagtail.blocks.TextBlock', (), {'help_text': 'Vizyon açıklaması', 'required': True}), 43: ('wagtail.blocks.TextBlock', (), {'help_text': 'Misyon açıklaması', 'required': True}), 44: ('wagtail.blocks.StructBlock', [[('vision', 42), ('mission', 43)]], {}), 45: ('wagtail.blocks.CharBlock', (), {'help_text': 'İkon CSS sınıfı (örn: icon-shield, icon-lightbulb)', 'required': True}), 46: ('wagtail.blocks.CharBlock', (), {'help_text': 'Değerin başlığı (örn: Deneyim ve Güven)', 'required': True}), 47: ('wagtail.blocks.TextBlock', (), {'help_text': 'Değerin kısa açıklaması', 'required': True}), 48: ('wagtail.blocks.StructBlock', [[('icon_class', 45), ('title', 46), ('description', 47)]], {}), 49: ('wagtail.blocks.ListBlock', (48,), {'help_text': 'Değerleri ekleyin (ikon + başlık + açıklama)'}), 50: ('wagtail.blocks.StructBlock', [[('items', 49)]], {}), 51: ('wagtail.blocks.StructBlock', [[('hero_section', 35), ('company_profile', 41), ('vision_mission', 44), ('values', 50)]], {}), 52: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 53: ('wagtail.blocks.CharBlock', (), {'default': 'Company Name', 'max_length': 120}), 54: ('wagtail.blocks.CharBlock', (), {'default': 'Work Description', 'max_length': 220}), 55: ('wagtail.blocks.URLBlock', (), {'help_text': 'Logo tıklandığında gidilecek URL', 'required': False}), 56: ('wagtail.blocks.StructBlock', [[('logo', 52), ('company_name', 53), ('work_description', 54), ('link', 55)]], {}), 57: ('wagtail.blocks.ListBlock', (56,), {'help_text': 'Slider’a eklenecek logolar', 'min_num': 1}), 58: ('wagtail.blocks.StructBlock', [[('logos', 57)]], {})}, help_text='The body of the page.', null=True)),
                ('thumbnail_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EmptyPageInPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('home_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='empty_in_pages', to='home.emptypage')),
                ('showcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeInPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('home_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_in_pages', to='home.homepage')),
                ('showcase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RobotsTxtSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='robots.txt içeriğini buradan düzenleyebilirsin.', verbose_name='robots.txt İçeriği')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
