# Generated by Django 5.2.7 on 2025-11-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_advert'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advert',
        ),
    ]
