# Generated by Django 5.2.7 on 2025-11-16 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_delete_advert'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='logo',
        ),
        migrations.AddField(
            model_name='homepage',
            name='navbar_style',
            field=models.CharField(choices=[('logo-left', 'Logo solda'), ('logo-center', 'Logo ortada'), ('logo-right', 'Logo sağda'), ('mega-menu', 'Mega Menü')], default='logo-center', max_length=50, verbose_name='Navbar Tasarımı'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='site_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Site Logosu'),
        ),
    ]
